version: '3'

services:

  wordpress:
    container_name: wp
    image: wordpress:5
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
    volumes:
      - wp_data:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/theme

  database:
    container_name: wp_db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  wp_data:
